Boutique:
  admin:
    name: Papa Mbaye BA
    email: ba.papa-mbaye@ugb.edu.sn
spring:
  application:
    name: Boutique
  datasource:
    username: maz
    password: sa123
    url: jdbc:mysql://localhost:3306/maz


  jpa:
    hibernate:
      #ddl-auto: create #### permet de supprimer toutes les tables et de les recréer
      ddl-auto: none
    show-sql: true

  profiles:
    active: ${Boutique:dev}