Boutique:
  admin:
    name: Equipe Dev
    email: dev@ugb.edu.sn
spring:
  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    url:  ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  h2:
    console:
      enabled: true
      path: /h2-console