Boutique:
  admin:
    name: Papa Mbaye BA
    email: ba.papa-mbaye@ugb.edu.sn
spring:
  application:
    name: Boutique
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}


  jpa:
    hibernate:
      #ddl-auto: create #### permet de supprimer toutes les tables et de les recréer
      ddl-auto: none
    show-sql: true

  profiles:
    active: ${SPRING_PROFILES_ACTIVE :dev}